/*
 * This file was generated by the Gradle 'init' task.
 */

import com.benjaminsproule.swagger.gradleplugin.model.ApiSourceExtension
import com.benjaminsproule.swagger.gradleplugin.model.InfoExtension
import com.benjaminsproule.swagger.gradleplugin.model.LicenseExtension
import com.benjaminsproule.swagger.gradleplugin.model.ScopeExtension
import com.benjaminsproule.swagger.gradleplugin.model.SecurityDefinitionExtension


plugins {
    java
    `maven-publish`
	id("org.springframework.boot") version "2.5.2"
	id("io.spring.dependency-management") version "1.0.11.RELEASE"
	id("com.github.johnrengelman.processes") version "0.5.0"
	id("org.springdoc.openapi-gradle-plugin") version "1.3.2"
	id("com.benjaminsproule.swagger") version "1.0.14"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

swagger {
    apiSource(
        closureOf<ApiSourceExtension> {
            springmvc = true
            locations = listOf("ashok.ids")
            schemes = listOf("http")
            host = "localhost:11101"
            basePath = "/"
            info(
                closureOf<InfoExtension> {
                    title = "Trusted Connector API"
                    version = project.version as String
                    license(
                        closureOf<LicenseExtension> {
                            url = "http://www.apache.org/licenses/LICENSE-2.0.html"
                            name = "Apache 2.0"
                        }
                    )
                    description = """This is the administrative REST API of the Trusted Connector.

The API provides an administrative interface to manage the Trusted Connector at runtime
and is used by the default administration dashboard ("web console").
"""
                }
            )
            swaggerDirectory = "${project.projectDir}/generated/swagger-ui"
            outputFormats = listOf("json", "yaml")
        }
    )
}


dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.7")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.4")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.11.4")
    implementation("org.json:json:20200518")
    implementation("org.apache.logging.log4j:log4j-api:2.13.3")
    implementation("org.apache.logging.log4j:log4j-core:2.13.3")
    implementation("org.apache.commons:commons-lang3:3.11")
    implementation("org.springdoc:springdoc-openapi-ui:1.5.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.7")
}

group = "ashok.ids.dataapps"
version = "0.0.1-SNAPSHOT"
description = "IDS Data-Apps Sample"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

openApi {
	apiDocsUrl.set("http://localhost:11101/api.json")
	outputFileName.set("api.json")
	outputDir.set(file("$buildDir/.."))
}
